"""Hermes plugin: family-inventory agent API (OpenAPI-driven).

The plugin parses the bundled `openapi.yaml` at load time and registers one
Hermes tool per OpenAPI operation. Tool name = operationId, description =
summary + description, parameters JSON Schema = synthesized from `parameters`
+ `requestBody.content."application/json".schema`. `$ref`s into
`#/components/schemas/` are resolved inline so the LLM sees concrete types.

Design principle: this file contains zero family-inventory domain knowledge.
All semantics live in openapi.yaml. To pick up upstream API changes, sync the
spec via update-openapi.sh and rebuild the Nix derivation.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Callable

from . import http as fi_http

logger = logging.getLogger(__name__)

TOOLSET = "family-inventory"
EMOJI = "📦"
# `$ref` recursion guard — protects against malicious or accidentally cyclic specs.
MAX_REF_DEPTH = 16


# ---------------------------------------------------------------------------
# OpenAPI loading
# ---------------------------------------------------------------------------


def _load_openapi() -> dict[str, Any]:
    """Read the bundled openapi.yaml. Prefer PyYAML; fall back to JSON.

    The spec is generated by `pnpm openapi:generate` in family-inventory. We
    keep it as YAML for diff readability, but the loader accepts JSON too in
    case a downstream consumer wants to swap formats.
    """
    spec_path = Path(__file__).resolve().parent / "openapi.yaml"
    raw = spec_path.read_text(encoding="utf-8")

    try:
        import yaml  # type: ignore[import-untyped]

        return yaml.safe_load(raw)
    except ImportError:
        logger.warning(
            "family-inventory: PyYAML not available; attempting JSON fallback"
        )
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                "family-inventory: cannot parse openapi.yaml — PyYAML missing "
                "and JSON fallback failed: " + str(exc)
            ) from exc


# ---------------------------------------------------------------------------
# JSON Schema synthesis
# ---------------------------------------------------------------------------


def _resolve_ref(
    node: Any,
    components: dict[str, Any],
    depth: int = 0,
) -> Any:
    """Inline `$ref` references that point into `#/components/schemas/...`.

    OpenAPI permits `$ref` at arbitrary depth; we recursively resolve while
    bounding depth to prevent runaway expansion on cyclic specs. Non-ref nodes
    pass through unchanged.
    """
    if depth >= MAX_REF_DEPTH:
        return {"type": "object", "additionalProperties": True}

    if isinstance(node, dict):
        if "$ref" in node and isinstance(node["$ref"], str):
            ref = node["$ref"]
            if not ref.startswith("#/"):
                logger.warning("family-inventory: external $ref not supported: %s", ref)
                return {"type": "object", "additionalProperties": True}
            target: Any = components
            # Walk #/components/schemas/Foo → components["components"]["schemas"]["Foo"]
            # Note: ref starts with "#/", so first segment after "#" is "components"
            for part in ref.lstrip("#/").split("/"):
                if not isinstance(target, dict) or part not in target:
                    logger.warning(
                        "family-inventory: unresolved $ref %s (stopped at %s)", ref, part
                    )
                    return {"type": "object", "additionalProperties": True}
                target = target[part]
            return _resolve_ref(target, components, depth + 1)

        # allOf is the typical compose pattern in the family-inventory spec
        # (e.g. `allOf: [{ $ref: ItemStatus }, { description: "..." }]`).
        # We merge children shallowly so the resulting schema is still a flat
        # JSON Schema the LLM can introspect.
        if "allOf" in node and isinstance(node["allOf"], list):
            merged: dict[str, Any] = {}
            for child in node["allOf"]:
                resolved = _resolve_ref(child, components, depth + 1)
                if isinstance(resolved, dict):
                    for k, v in resolved.items():
                        if k == "properties" and isinstance(v, dict):
                            merged.setdefault("properties", {}).update(v)
                        elif k == "required" and isinstance(v, list):
                            merged.setdefault("required", []).extend(v)
                        else:
                            merged.setdefault(k, v)
            # Carry over sibling keys from the original node (e.g. description override)
            for k, v in node.items():
                if k == "allOf":
                    continue
                merged[k] = v
            return _resolve_ref(merged, components, depth + 1)

        # Plain dict: walk children
        return {k: _resolve_ref(v, components, depth + 1) for k, v in node.items()}

    if isinstance(node, list):
        return [_resolve_ref(v, components, depth + 1) for v in node]

    return node


def _build_parameters_schema(
    operation: dict[str, Any],
    spec_root: dict[str, Any],
) -> tuple[dict[str, Any], list[str], list[str], bool]:
    """Synthesize a JSON Schema for the operation's parameters.

    Returns (json_schema, path_param_names, query_param_names, has_body).
    The schema is flat — path / query / body fields all live at the top level
    of `properties` so Hermes can pass them through as kwargs.
    """
    properties: dict[str, Any] = {}
    required: list[str] = []
    path_param_names: list[str] = []
    query_param_names: list[str] = []
    has_body = False

    for param in operation.get("parameters") or []:
        resolved = _resolve_ref(param, spec_root)
        if not isinstance(resolved, dict):
            continue
        name = resolved.get("name")
        location = resolved.get("in")
        if not name or location not in ("path", "query"):
            continue
        schema = resolved.get("schema") or {"type": "string"}
        schema = _resolve_ref(schema, spec_root)
        if not isinstance(schema, dict):
            schema = {"type": "string"}
        # OpenAPI parameter-level description trumps inline schema description
        # when both are set, so callers see the most specific guidance.
        if resolved.get("description") and "description" not in schema:
            schema = {**schema, "description": resolved["description"]}
        properties[name] = schema
        if resolved.get("required"):
            required.append(name)
        if location == "path":
            path_param_names.append(name)
            # Path params are always required by OpenAPI rules.
            if name not in required:
                required.append(name)
        else:
            query_param_names.append(name)

    request_body = operation.get("requestBody")
    if isinstance(request_body, dict):
        resolved_body = _resolve_ref(request_body, spec_root)
        content = (resolved_body or {}).get("content") or {}
        json_schema = (content.get("application/json") or {}).get("schema")
        if json_schema is not None:
            resolved_schema = _resolve_ref(json_schema, spec_root)
            if isinstance(resolved_schema, dict):
                has_body = True
                body_props = resolved_schema.get("properties") or {}
                if isinstance(body_props, dict):
                    for k, v in body_props.items():
                        # Body fields shadow same-named params only if not
                        # already taken by path/query (shouldn't happen in
                        # practice — names are namespaced by API design).
                        properties.setdefault(k, v)
                body_required = resolved_schema.get("required") or []
                if isinstance(body_required, list):
                    for k in body_required:
                        if k not in required:
                            required.append(k)

    schema: dict[str, Any] = {
        "type": "object",
        "properties": properties,
        # Reject unknown kwargs — keeps the LLM honest about the contract and
        # surfaces typos as validation errors rather than silent drops.
        "additionalProperties": False,
    }
    if required:
        schema["required"] = required

    return schema, path_param_names, query_param_names, has_body


# ---------------------------------------------------------------------------
# Handler factory
# ---------------------------------------------------------------------------


def _make_handler(
    *,
    method: str,
    path_template: str,
    path_param_names: list[str],
    query_param_names: list[str],
    has_body: bool,
    operation_id: str,
) -> Callable[..., str]:
    """Build the handler closure for a single OpenAPI operation.

    Returns a JSON-encoded string per Hermes tool conventions. Hermes invokes
    handlers as `handler(args, **kwargs)` where `args` is the LLM-supplied
    parameter dict — we accept both that shape and bare kwargs for safety.
    """
    path_set = set(path_param_names)
    query_set = set(query_param_names)

    def handler(args: dict[str, Any] | None = None, **kwargs: Any) -> str:
        merged: dict[str, Any] = {}
        if isinstance(args, dict):
            merged.update(args)
        merged.update(kwargs)

        path_params: dict[str, Any] = {}
        query_params: dict[str, Any] = {}
        body: dict[str, Any] = {}

        for k, v in merged.items():
            if v is None:
                continue
            if k in path_set:
                path_params[k] = v
            elif k in query_set:
                query_params[k] = v
            elif has_body:
                body[k] = v
            # Unknown keys: ignore silently. The JSON Schema declares
            # additionalProperties=false, so well-behaved LLMs won't send any;
            # tolerating stray keys here keeps misbehaving callers from
            # crashing the entire tool call.

        try:
            response = fi_http.request(
                method=method,
                path_template=path_template,
                path_params=path_params,
                query_params=query_params,
                json_body=body if (has_body and body) else None,
            )
        except Exception as exc:  # pragma: no cover - defensive
            logger.exception(
                "family-inventory: handler %s raised unexpectedly", operation_id
            )
            return json.dumps(
                {
                    "error": f"handler internal error: {type(exc).__name__}: {exc}",
                    "operation_id": operation_id,
                },
                ensure_ascii=False,
            )

        return json.dumps(response, ensure_ascii=False, default=str)

    handler.__name__ = f"family_inventory_{operation_id}"
    handler.__doc__ = f"OpenAPI handler for {method.upper()} {path_template}"
    return handler


# ---------------------------------------------------------------------------
# Description synthesis
# ---------------------------------------------------------------------------


def _build_description(operation: dict[str, Any], method: str, path: str) -> str:
    summary = (operation.get("summary") or "").strip()
    description = (operation.get("description") or "").strip()
    parts: list[str] = []
    if summary:
        parts.append(summary)
    parts.append(f"`{method.upper()} {path}`")
    if description and description != summary:
        parts.append(description)
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Plugin entry point
# ---------------------------------------------------------------------------


HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def register(ctx) -> None:
    """Plugin entry point — invoked once by the Hermes plugin loader.

    Parses the bundled OpenAPI spec and registers one tool per operation. A
    parse failure on a single operation is logged and skipped — the plugin
    stays loadable and remaining operations still register.
    """
    try:
        spec = _load_openapi()
    except Exception:
        logger.exception(
            "family-inventory: failed to load openapi.yaml; plugin disabled"
        )
        return

    if not isinstance(spec, dict):
        logger.error("family-inventory: openapi.yaml is not a mapping; plugin disabled")
        return

    paths = spec.get("paths") or {}
    if not isinstance(paths, dict):
        logger.error("family-inventory: openapi.paths missing/invalid; plugin disabled")
        return

    base_url_hint = os.environ.get(fi_http.ENV_BASE_URL, "(unset)")
    actor_hint = os.environ.get(fi_http.ENV_ACTOR, "(unset)")
    logger.info(
        "family-inventory: registering tools (api_url=%s, actor=%s)",
        base_url_hint,
        actor_hint,
    )

    registered = 0
    skipped = 0

    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method.lower() not in HTTP_METHODS:
                continue
            if not isinstance(operation, dict):
                continue

            operation_id = operation.get("operationId")
            if not operation_id or not isinstance(operation_id, str):
                logger.warning(
                    "family-inventory: skipping %s %s — missing operationId",
                    method.upper(),
                    path,
                )
                skipped += 1
                continue

            try:
                schema, path_params, query_params, has_body = _build_parameters_schema(
                    operation, spec
                )
            except Exception:
                logger.exception(
                    "family-inventory: skipping %s — schema build failed",
                    operation_id,
                )
                skipped += 1
                continue

            handler = _make_handler(
                method=method,
                path_template=path,
                path_param_names=path_params,
                query_param_names=query_params,
                has_body=has_body,
                operation_id=operation_id,
            )

            tool_schema = {
                "name": operation_id,
                "description": _build_description(operation, method, path),
                "parameters": schema,
            }

            try:
                ctx.register_tool(
                    name=operation_id,
                    toolset=TOOLSET,
                    schema=tool_schema,
                    handler=handler,
                    emoji=EMOJI,
                )
                registered += 1
            except Exception:
                logger.exception(
                    "family-inventory: ctx.register_tool failed for %s", operation_id
                )
                skipped += 1

    logger.info(
        "family-inventory: registered %d tools (%d skipped)", registered, skipped
    )
